Repository hyprutils/hyprlauncher, pull requests merged in 2024-10, with the labels that each got.

#5 📂 fix: don't close the app on dir clicked
  src/ui.rs
Labels: gui

#6 add config parsing
  src/config.rs
Labels: backend

#8 limit shown results to 100
  src/config.rs
  src/search.rs
Labels: refactor, performance, gui

#9 move caret infront of latest word when selecting a dir
  src/ui.rs
Labels: refactor, gui

#10 change selection color to grey
  src/config.rs
Labels: gui

#11 fix selection color
  src/config.rs
Labels: bug, gui

#12 v0.1.1
  Cargo.lock
  Cargo.toml
Labels: skip-changelog

#17 only show desktop files in non search view
  src/launcher.rs
  src/search.rs
Labels: refactor, performance, gui, rust

#21 v0.1.2
  Cargo.lock
  Cargo.toml
Labels: backend

#22 docs: add a logo
  hyprlauncher.png
  hyprlauncher.svg
  readme.md
Labels: documentation

#23 add descriptions
  src/launcher.rs
  src/ui.rs
Labels: enhancement, gui, rust

#24 make descriptions and paths configurable
  src/config.rs
  src/ui.rs
Labels: enhancement, refactor, gui, rust

#25 font size should be configurable only inside of the css file
  src/config.rs
Labels: refactor, backend, rust

#26 add .. directory to every dir
  src/search.rs
Labels: enhancement, gui, rust

#28 refact: read paths from `XDG_DATA_DIRS`
  src/launcher.rs
Labels: refactor

#30 make descriptions off by def
  src/config.rs
Labels: gui, backend
