Repository hyprutils/hyprlauncher, pull requests merged in 2024-12, with the labels that each got.

#114 Resolve all issues
  Cargo.lock
  Cargo.toml
  configuration.md
  src/app.rs
  src/config.rs
  src/launcher.rs
  src/main.rs
  src/search.rs
  src/ui.rs
Labels: bug, enhancement, refactor, gui, backend, rust

#116 add websearch functionality
  Cargo.lock
  Cargo.toml
  configuration.md
  src/config.rs
  src/search.rs
Labels: enhancement, gui, rust

#119 add live css reloading
  src/app.rs
  src/config.rs
Labels: enhancement, gui, rust

#122 fix desync from searchbar when entering a dir
  src/ui.rs
Labels: bug, gui, rust

#123 fix path issues
  src/search.rs
Labels: bug, gui, rust

#127 show actions when actively searching instead of requiring the full application name
  configuration.md
  src/config.rs
  src/search.rs
Labels: refactor, gui, rust

#128 fix error
  src/app.rs
Labels: bug, gui

#133 basic custom search engine functionality
  configuration.md
  src/config.rs
  src/search.rs
Labels: enhancement, gui, rust

#134 add experimental context aware mapping
  Cargo.lock
  Cargo.toml
  configuration.md
  src/config.rs
  src/launcher.rs
  src/main.rs
  src/search.rs
  src/ui.rs
Labels: enhancement, gui, rust

#139 sort non heatmap entries alphabetically
  src/search.rs
Labels: bug, gui, rust

#141 switch to toml
  Cargo.lock
  Cargo.toml
  configuration.md
  src/config.rs
  src/launcher.rs
Labels: enhancement, refactor, rust

#142 add custom error overlay
  configuration.md
  src/app.rs
  src/config.rs
  src/ui.rs
Labels: enhancement, refactor, gui, rust

#149 prioritize showing categories before individual entries
  src/config.rs
Labels: bug, gui, rust

#150 resolve #146 #145
  src/config.rs
  src/search.rs
Labels: bug, enhancement, refactor, gui, rust

#88 feat: calculation
  Cargo.lock
  Cargo.toml
  configuration.md
  src/config.rs
  src/search.rs
Labels: enhancement

#157 fix uppercase searching
  src/search.rs
Labels: bug

#158 remove if results.is_empty() conditional
  src/search.rs
Labels: bug
