Repository hyprutils/hyprlauncher, pull requests merged in 2024-11, with the labels that each got.

#31 docs: update the wording
  readme.md
Labels: documentation

#33 fix incorrect repo
  Cargo.toml
Labels: backend, rust

#38 remove image entries for entries that dont have an icon
  src/launcher.rs
  src/ui.rs
Labels: refactor, performance, gui

#39 only show bin entry when full name is specified
  Cargo.lock
  src/search.rs
Labels: refactor, performance, gui, rust

#40 remove debounce
  src/ui.rs
Labels: refactor, gui

#42 insert dummy entry when no results are found
  src/ui.rs
Labels: refactor, gui, rust

#44 fix app launching
  src/launcher.rs
  src/ui.rs
Labels: bug, gui, rust

#45 move theming to css
  src/config.rs
  src/ui.rs
Labels: refactor, gui, rust

#46 make vim keys togglable
  src/config.rs
  src/ui.rs
Labels: enhancement, gui, rust

#47 make search bar togglable
  src/config.rs
  src/ui.rs
Labels: enhancement, gui, rust

#49 optimize launch times
  src/app.rs
  src/launcher.rs
  src/ui.rs
Labels: refactor, performance, gui, backend

#51 switch to gtk4 layer shell
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  readme.md
  src/config.rs
  src/ui.rs
Labels: enhancement, refactor, gui

#52 add rounded corner configuration
  src/config.rs
Labels: enhancement, gui, rust

#54 add more customization
  src/config.rs
Labels: enhancement, refactor, gui, rust

#55 nest window modules
  src/config.rs
  src/ui.rs
Labels: refactor, gui, rust

#56 add border settings
  src/config.rs
Labels: enhancement, gui, rust

#57 add an option to hide the scroll bar
  src/config.rs
  src/ui.rs
Labels: enhancement, gui, rust

#59 optimize entry parsing
  Cargo.lock
  Cargo.toml
  src/launcher.rs
Labels: refactor, performance, gui, backend, rust

#60 optimize search functionality
  src/launcher.rs
  src/search.rs
  src/ui.rs
Labels: refactor, performance, gui, rust

#61 optimize gui building
  src/config.rs
  src/ui.rs
Labels: refactor, performance, gui, backend, rust

#64 perf: clean up the deps
  Cargo.lock
  Cargo.toml
  src/config.rs
  src/launcher.rs
  src/ui.rs
Labels: refactor, backend, rust

#67 allow execution of bin executables with arguments
  src/config.rs
  src/search.rs
Labels: enhancement, gui, rust

#68 improve launch times
  Cargo.lock
  Cargo.toml
  src/app.rs
  src/main.rs
  src/ui.rs
Labels: refactor, performance, gui, rust

#69 add gtk theming override
  src/config.rs
Labels: enhancement, gui, rust

#72 clear search and focus search bar after app is closed
  src/ui.rs
Labels: refactor, gui, rust

#73 add live config reloading
  Cargo.lock
  Cargo.toml
  src/app.rs
  src/config.rs
  src/launcher.rs
  src/main.rs
  src/ui.rs
Labels: enhancement, gui, rust

#74 add debug section
  src/config.rs
  src/ui.rs
Labels: enhancement, gui, rust

#75 fix config merging
  src/config.rs
Labels: bug, gui, rust

#76 semi fix keystroke config loading spam
  src/ui.rs
Labels: bug, performance, gui, rust

#78 properly hide and show search bar on live config reload
  src/ui.rs
Labels: bug, gui, rust

#79 switch to freedesktop entry parser
  Cargo.lock
  Cargo.toml
  src/launcher.rs
Labels: refactor, performance, gui, rust

#80 semi-rewrite of hyprlauncher
  src/config.rs
  src/launcher.rs
  src/search.rs
  src/ui.rs
Labels: refactor, performance, gui, rust

#81 add custom navigation key support
  configuration.md
  src/config.rs
  src/ui.rs
Labels: enhancement, gui, rust

#82 fix: set theme css to higher priority
  src/ui.rs
Labels: bug, gui, rust

#83 refact(?!config): improve error handling & readability
  src/app.rs
  src/launcher.rs
  src/main.rs
  src/search.rs
  src/ui.rs
Labels: refactor, rust

#92 fix: use $XDG_RUNTIME_DIR instead of /tmp
  src/app.rs
Labels: refactor, rust

#97 fix(search): don't defocus when arrow keys are pressed
  src/ui.rs
Labels: bug, gui, rust

#95 fix: correctly display icons from absolute paths
  src/ui.rs
Labels: bug, rust

#112 docs: add the Grind badge
  readme.md
Labels: documentation
